wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [42, 42, 42, 42]
    rows: [8, 8, 8, 4, 4]
  refreshInterval: 1
  mods:
    worldclock:
      title: 'World Clock'
      type: 'clocks'
      enabled: true
      colors:
        rows:
          even: 'lightblue'
          odd: 'white'
      locations:
        Cupertino: 'America/Los_Angeles'
        'New York': 'America/New_York'
        Paris: 'Europe/Paris'
        'Ho Chi Minh': 'Asia/Ho_Chi_Minh'
        Singapore: 'Asia/Singapore'
        Tokyo: 'Asia/Tokyo'
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: 'chronological'

    prettyweather:
      enabled: true
      city: 'Ho Chi Minh City'
      units: 'm'
      view: 0
      language: 'en'
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 5m

    ipinfo:
      type: ipinfo
      colors:
        name: 'lightblue'
        value: 'white'
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 150

    hackernews:
      enabled: true
      numberOfStories: 10
      position:
        top: 1
        left: 0
        height: 2
        width: 2
      storyType: top
      refreshInterval: 900

    power:
      enabled: true
      position:
        top: 0
        left: 3
        height: 1
        width: 1
      refreshInterval: 15

    resourceusage:
      enabled: true
      showMem: true
      cpuCombined: true
      position:
        top: 3
        left: 2
        height: 1
        width: 2
      refreshInterval: 5

    github:
      enabled: false
      apiKey: 'REDACTED'
      baseURL: ''
      enableStatus: true
      position:
        top: 3
        left: 0
        height: 2
        width: 2
      refreshInterval: 300
      repositories:
        - 'trongthanh/int3ractive.com'
      username: 'trongthanh'

    feedreader:
      enabled: true
      feeds:
        - https://www.reddit.com/r/programming.rss
      feedLimit: 10
      refreshInterval: 2h
      position:
        top: 3
        left: 0
        height: 2
        width: 2

    gcal:
      colors:
        title: 'lightblue'
        description: 'lightgreen'
        highlights:
          - ['1on1|1:1|1 on 1', 'green']
          - ['lunch', 'yellow']
          - ['meeting', 'red']
      conflictIcon: '🚨'
      currentIcon: '💥'
      displayResponseStatus: true
      email: 'email@example.com'
      enabled: true
      eventCount: 15
      multiCalendar: true
      position:
        top: 1
        left: 2
        height: 2
        width: 2
      refreshInterval: 300
      secretFile: '/path/to/secret.json'
      showDeclined: true
      showEndTime: false
      withLocation: true

    urlcheck:
      enabled: true
      position:
        top: 4
        left: 2
        height: 1
        width: 2
      refreshInterval: 1m
      urls:
        - https://int3ractive.com
        - https://nuoidaycon.blog
